### ISSUE TITLE
pcl fails to compile using vtk 6.0 on OS X 10.9

### ISSUE THREAD

**Issue by tanuva** [ros/homebrew-hydro#3]
PCL from git is supposed to build against vtk 6.0: http://www.pcl-users.org/vtk-error-when-making-PCL1-7-from-source-td4029769.html
This is a patched vtk recipe for OS X 10.9 that I used: https://raw.github.com/jenshnielsen/homebrew-science/vtk6mavericks/vtk.rb

Is it necessary to wait for a new pcl release or could reciping the git version work?

Build log:

```
[ 19%] Building CXX object io/CMakeFiles/pcl_io.dir/src/vtk_lib_io.cpp.o
brew: superenv removed: -Wno-invalid-offsetof
brew: superenv added: -pipe -w -Os -march=native -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
/tmp/pcl-0khd/pcl-pcl-1.7.0/io/src/vtk_lib_io.cpp:181:16: error: no member named 'SetInput' in
      'vtkPolyDataWriter'; did you mean 'GetInput'?
  poly_writer->SetInput (poly_data);
               ^~~~~~~~
               GetInput
/usr/local/include/vtk-6.0/vtkPolyDataWriter.h:39:16: note: 'GetInput' declared here
  vtkPolyData* GetInput();
               ^
/tmp/pcl-0khd/pcl-pcl-1.7.0/io/src/vtk_lib_io.cpp:181:26: error: too many arguments to function call, expected
      0, have 1
  poly_writer->SetInput (poly_data);
  ~~~~~~~~~~~~~~~~~~~~~  ^~~~~~~~~
/usr/local/include/vtk-6.0/vtkPolyDataWriter.h:39:3: note: 'GetInput' declared here
  vtkPolyData* GetInput();
  ^
/tmp/pcl-0khd/pcl-pcl-1.7.0/io/src/vtk_lib_io.cpp:197:16: error: no member named 'SetInput' in 'vtkPLYWriter';
      did you mean 'GetInput'?
  poly_writer->SetInput (poly_data);
               ^~~~~~~~
               GetInput
/usr/local/include/vtk-6.0/vtkPLYWriter.h:122:16: note: 'GetInput' declared here
  vtkPolyData* GetInput();
               ^
/tmp/pcl-0khd/pcl-pcl-1.7.0/io/src/vtk_lib_io.cpp:197:26: error: too many arguments to function call, expected
      0, have 1
  poly_writer->SetInput (poly_data);
  ~~~~~~~~~~~~~~~~~~~~~  ^~~~~~~~~
/usr/local/include/vtk-6.0/vtkPLYWriter.h:122:3: note: 'GetInput' declared here
  vtkPolyData* GetInput();
  ^
/tmp/pcl-0khd/pcl-pcl-1.7.0/io/src/vtk_lib_io.cpp:212:14: error: no member named 'Update' in 'vtkPolyData'
  poly_data->Update ();
  ~~~~~~~~~  ^
/tmp/pcl-0khd/pcl-pcl-1.7.0/io/src/vtk_lib_io.cpp:214:16: error: no member named 'SetInput' in 'vtkSTLWriter';
      did you mean 'GetInput'?
  poly_writer->SetInput (poly_data);
               ^~~~~~~~
               GetInput
/usr/local/include/vtk-6.0/vtkSTLWriter.h:45:16: note: 'GetInput' declared here
  vtkPolyData* GetInput();
               ^
/tmp/pcl-0khd/pcl-pcl-1.7.0/io/src/vtk_lib_io.cpp:214:26: error: too many arguments to function call, expected
      0, have 1
  poly_writer->SetInput (poly_data);
  ~~~~~~~~~~~~~~~~~~~~~  ^~~~~~~~~
/usr/local/include/vtk-6.0/vtkSTLWriter.h:45:3: note: 'GetInput' declared here
  vtkPolyData* GetInput();
  ^
/tmp/pcl-0khd/pcl-pcl-1.7.0/io/src/vtk_lib_io.cpp:486:39: error: too few arguments to function call, expected
      2, have 1
  image->SetNumberOfScalarComponents(1);
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
/usr/local/include/vtk-6.0/vtkImageData.h:298:3: note: 'SetNumberOfScalarComponents' declared here
  static void SetNumberOfScalarComponents( int n, vtkInformation* meta_data);
  ^
/tmp/pcl-0khd/pcl-pcl-1.7.0/io/src/vtk_lib_io.cpp:487:10: error: no member named 'SetScalarTypeToFloat' in
      'vtkImageData'
  image->SetScalarTypeToFloat();
  ~~~~~  ^
/tmp/pcl-0khd/pcl-pcl-1.7.0/io/src/vtk_lib_io.cpp:488:10: error: no matching member function for call to
      'AllocateScalars'
  image->AllocateScalars();
  ~~~~~~~^~~~~~~~~~~~~~~
/usr/local/include/vtk-6.0/vtkImageData.h:237:16: note: candidate function not viable: requires 2 arguments,
      but 0 were provided
  virtual void AllocateScalars(int dataType, int numComponents);
               ^
/usr/local/include/vtk-6.0/vtkImageData.h:244:16: note: candidate function not viable: requires single
      argument 'pipeline_info', but no arguments were provided
  virtual void AllocateScalars(vtkInformation* pipeline_info);
               ^
/tmp/pcl-0khd/pcl-pcl-1.7.0/io/src/vtk_lib_io.cpp:507:47: error: no member named 'GetProducerPort' in
      'vtkImageData'
  shiftScaleFilter->SetInputConnection(image->GetProducerPort());
                                       ~~~~~  ^
11 errors generated.
make[2]: *** [io/CMakeFiles/pcl_io.dir/src/vtk_lib_io.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [io/CMakeFiles/pcl_io.dir/all] Error 2
make: *** [all] Error 2
==> Formula
Tap: ros/hydro
Path: /usr/local/Library/Taps/ros-hydro/pcl.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
HEAD: c35067b6710098ee39533129995703ee629574b2
CPU: dual-core 64-bit ivybridge
OS X: 10.9-x86_64
Xcode: 5.0.1
CLT: 5.0.1.0.1.1382131676
X11: 2.7.4 => /opt/X11
==> ENV
HOMEBREW_CC: clang
MAKEFLAGS: -j2
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers:/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_PATH: /usr/local/opt/eigen/lib/pkgconfig:/usr/local/opt/flann/lib/pkgconfig:/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.9
HOMEBREW_VERBOSE: 1
ACLOCAL_PATH: /usr/local/share/aclocal
OBJC: cc
PATH: /usr/local/opt/python/bin:/usr/local/Library/ENV/4.3:/usr/local/opt/cmake/bin:/usr/local/opt/hdf5/bin:/usr/local/opt/vtk/bin:/usr/local/opt/qhull/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: pcl did not build
```
