### ISSUE TITLE
pcl 1.7.1 fails to compile on Mountain Lion (10.8.5)

### ISSUE THREAD

**Issue by scpeters** [ros/homebrew-hydro#19]
I'm following the [ros hydro instructions](http://wiki.ros.org/hydro/Installation/OSX/Homebrew/Source), and I had just installed vtk5, but now pcl 1.7.1 won't install.

It's giving a screenful of compilation errors like the following:

```
[ 11%] Built target pcl_plyheader
/tmp/pcl-0T3b/pcl-pcl-1.7.1/io/tools/ply/ply2ply.cpp:356:17: error: no member named 'at' in namespace 'pcl::io::ply'
  pcl::io::ply::at<pcl::io::ply::int8>(scalar_property_definition_callbacks) = boost::bind(&ply_to_ply_converter::scalar_property_definition_callback<pcl::io::ply::int8>, this, _1, _2);
  ~~~~~~~~~~~~~~^
/tmp/pcl-0T3b/pcl-pcl-1.7.1/io/tools/ply/ply2ply.cpp:356:38: error: expected '(' for function-style cast or type construction
  pcl::io::ply::at<pcl::io::ply::int8>(scalar_property_definition_callbacks) = boost::bind(&ply_to_ply_converter::scalar_property_definition_callback<pcl::io::ply::int8>, this, _1, _2);
                   ~~~~~~~~~~~~~~~~~~^
...
```

The strange thing is that this matches some [old errors from 2012 that were supposedly fixed in version 1.6](http://www.pcl-users.org/Problems-compiling-from-source-on-Mac-OS-X-Lion-td3862799.html). Has anyone successfully built pcl recently on Mountain Lion?

My configuration:

```
==> Formula
Tap: ros/hydro
Path: /usr/local/Library/Taps/ros-hydro/pcl.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
HEAD: 7b68e440f1626fc17a33afb2784404139cafd24c
CPU: 8-core 64-bit ivybridge
OS X: 10.8.5-x86_64
Xcode: 5.1
CLT: 5.1.0.0.1.1393561416
X11: 2.7.5 => /opt/X11
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /usr/local/opt/qt/Frameworks
PKG_CONFIG_PATH: /usr/local/opt/eigen/lib/pkgconfig:/usr/local/opt/flann/lib/pkgconfig:/usr/local/opt/qt/lib/pkgconfig:/usr/local/opt/glew/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.8
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/local/opt/cmake/bin:/usr/local/opt/hdf5/bin:/usr/local/opt/qt/bin:/usr/local/opt/vtk5/bin:/usr/local/opt/qhull/bin:/usr/local/opt/glew/bin:/usr/bin:/bin:/usr/sbin:/sbin
```
